version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./DB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
  api:
    build: .
    image: yfirroloni/showerthoughts  # goes to my user DockerHub registry
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
