version: '3'
services:
  db:
    read_only: false
    image: postgres
    volumes:
      - ./DB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
  api:
    read_only: false
    image: yfirroloni/showerthoughts  # goes to my user DockerHub registry
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

